const products = [
    // shop0
    {
        shop: {
            address: "999 Quang Trung",
            avatarImg: "https://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2FshopAvatar0.png?alt=media&token=8e14ae91-5f16-4ac5-a84e-f4e95cfb6b84",
            backgroundImg: "https://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2FshopBg0.jpg?alt=media&token=e3f44012-26ce-4ab6-a92a-ac5583f8e003",
            city: "Kon Tum",
            district: "Sa Thầy",
            name: "Shop 0",
            userId: "jb5n1dhF7geNMX8TVHnjCFwOvdo2",
            ward: "Thị trấn Sa Thầy",
        },
        name: 'Acoustic Epiphone DR-100 Natural',
        standardCost: 2500000,
        salePrice: 3500000,
        quantity: 2000,
        soldQuantity: 350,
        rating: 4.8,
        type: 1,
        img: [
            'https://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2Fguitar1_1.jpg?alt=media&token=1f7209dc-d6f2-46f5-a896-a1d0436b8dd8',
            'https://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2Fguitar1_2.jpg?alt=media&token=aa9a1b01-5125-46c2-9a66-bfff3c244d82',
            'shttps://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2Fguitar1_3.jpg?alt=media&token=b7587773-5cfa-4696-89b4-89aa380d013a',
            'https://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2Fguitar1_4.jpg?alt=media&token=912cafc0-cb14-4861-9606-bfdce4efcf54',
            'https://firebasestorage.googleapis.com/v0/b/gita-backend.appspot.com/o/server%2Fguitar1_5.jpg?alt=media&token=9bab5d0f-1b50-48b0-af06-ee03b0e8e903'
        ],
        // discountId1
        discount: {
            id: 'TghBgAqBdYpgXvPE2ojQ',
            name: "Giảm giá hè(shop0) 1",
            percent: 0.2
        },
        specifications: {
            brand: 'Epiphone',
            origin: 'USA',
            shape: 'D Đầy',
            paintStyle: 'Sơn Bóng',
            top: 'Gỗ Vân Sam(Select Spruce)',
            sideAndBack: 'Gỗ Gụ (Select Mahogany)',
            headstockAndNeck: 'Gỗ Okoume',
            saddle: 'Gỗ Cẩm Lai (Rosewood)',
            string: 'DAddario',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Nhiều người mới học hoặc chưa bao giờ học guitar thường có tâm lý tìm mua một cây đàn "bình thường" để tập, sau này chơi tốt sẽ đổi sang cây đàn tốt hơn. Tuy nhiên, thế nào là cây đàn "bình thường" thì lại là điều khó định nghĩa, có người nói đàn gỗ thông, kỹ thuật sản xuất vừa phải, tầm giá khoảng 1 triệu là vừa. Người khác lại cho rằng giai đoạn đầu là quan trọng nhất, vì giống như em bé tập nói, nếu người dạy nói sai thì sẽ nói sai mãi sau này. Cây đàn đầu tiên quyết định khả năng thẩm âm, độ tinh tế của đôi tai người chơi ngay giai đoạn đầu, nên phải mua đàn tốt, nếu không sẽ "hỏng tai", sau này chơi suốt ngày phải nhìn vào bản nhạc... Nói chung, mỗi người có ý kiến và một tiêu chuẩn khác nhau.'
    },
    {
        shopId: '-N5orBlfPXJ49qk6nOh_',
        name: 'Acoustic Epiphone DR-100 Natural 222',
        standardCost: 2500000,
        salePrice: 3250000,
        quantity: 3124,
        soldQuantity: 1234,
        rating: 4.5,
        type: 1,
        img: ['server/guitar1_1.jpg', 'server/guitar1_2.jpg', 'server/guitar1_3.jpg', 'server/guitar1_4.jpg', 'server/guitar1_5.jpg'],
        // discountId2
        discountId: '-N5ordCFE49c0IgaAIuI',
        specifications: {
            brand: 'Epiphone',
            origin: 'USA',
            shape: 'D Đầy',
            paintStyle: 'Sơn Bóng',
            top: 'Gỗ Vân Sam(Select Spruce)',
            sideAndBack: 'Gỗ Gụ (Select Mahogany)',
            headstockAndNeck: 'Gỗ Okoume',
            saddle: 'Gỗ Cẩm Lai (Rosewood)',
            string: 'DAddario',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Nhiều người mới học hoặc chưa bao giờ học guitar thường có tâm lý tìm mua một cây đàn "bình thường" để tập, sau này chơi tốt sẽ đổi sang cây đàn tốt hơn. Tuy nhiên, thế nào là cây đàn "bình thường" thì lại là điều khó định nghĩa, có người nói đàn gỗ thông, kỹ thuật sản xuất vừa phải, tầm giá khoảng 1 triệu là vừa. Người khác lại cho rằng giai đoạn đầu là quan trọng nhất, vì giống như em bé tập nói, nếu người dạy nói sai thì sẽ nói sai mãi sau này. Cây đàn đầu tiên quyết định khả năng thẩm âm, độ tinh tế của đôi tai người chơi ngay giai đoạn đầu, nên phải mua đàn tốt, nếu không sẽ "hỏng tai", sau này chơi suốt ngày phải nhìn vào bản nhạc... Nói chung, mỗi người có ý kiến và một tiêu chuẩn khác nhau.'
    },
    {
        shopId: '-N5orBlfPXJ49qk6nOh_',
        name: 'Acoustic Epiphone DR-100 Natural 333',
        standardCost: 2500000,
        salePrice: 2900000,
        quantity: 1242,
        soldQuantity: 222,
        rating: 4.1,
        type: 1,
        img: ['server/guitar1_1.jpg', 'server/guitar1_2.jpg', 'server/guitar1_3.jpg', 'server/guitar1_4.jpg', 'server/guitar1_5.jpg'],
        // discountId1
        discountId: '-N5oraR5kzENkMFWUBy0',
        specifications: {
            brand: 'Epiphone',
            origin: 'USA',
            shape: 'D Đầy',
            paintStyle: 'Sơn Bóng',
            top: 'Gỗ Vân Sam(Select Spruce)',
            sideAndBack: 'Gỗ Gụ (Select Mahogany)',
            headstockAndNeck: 'Gỗ Okoume',
            saddle: 'Gỗ Cẩm Lai (Rosewood)',
            string: 'DAddario',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Nhiều người mới học hoặc chưa bao giờ học guitar thường có tâm lý tìm mua một cây đàn "bình thường" để tập, sau này chơi tốt sẽ đổi sang cây đàn tốt hơn. Tuy nhiên, thế nào là cây đàn "bình thường" thì lại là điều khó định nghĩa, có người nói đàn gỗ thông, kỹ thuật sản xuất vừa phải, tầm giá khoảng 1 triệu là vừa. Người khác lại cho rằng giai đoạn đầu là quan trọng nhất, vì giống như em bé tập nói, nếu người dạy nói sai thì sẽ nói sai mãi sau này. Cây đàn đầu tiên quyết định khả năng thẩm âm, độ tinh tế của đôi tai người chơi ngay giai đoạn đầu, nên phải mua đàn tốt, nếu không sẽ "hỏng tai", sau này chơi suốt ngày phải nhìn vào bản nhạc... Nói chung, mỗi người có ý kiến và một tiêu chuẩn khác nhau.'
    },

    {
        shopId: '-N5orBlfPXJ49qk6nOh_',
        name: 'Acoustic Rosen Xanh Đá G11SC',
        standardCost: 1500000,
        salePrice: 2300000,
        quantity: 1242,
        soldQuantity: 222,
        rating: 4.5,
        type: 1,
        img: ['server/guitar2_1.jpg', 'server/guitar2_2.jpg', 'server/guitar2_3.jpg', 'server/guitar2_4.jpg'],
        // discountId1
        discountId: '-N5orer-LorD7Z6lP83n',
        specifications: {
            brand: 'Rosen',
            origin: 'Trung Quốc',
            shape: 'D Thiếu',
            paintStyle: 'Sơn Mờ',
            top: 'Gỗ thông nguyên miếng',
            sideAndBack: 'Gỗ Gụ (Select Mahogany)',
            headstockAndNeck: 'Gỗ Nato',
            saddle: 'HPL',
            string: 'Rosen OEM',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Nhiều người mới học hoặc chưa bao giờ học guitar thường có tâm lý tìm mua một cây đàn "bình thường" để tập, sau này chơi tốt sẽ đổi sang cây đàn tốt hơn. Tuy nhiên, thế nào là cây đàn "bình thường" thì lại là điều khó định nghĩa, có người nói đàn gỗ thông, kỹ thuật sản xuất vừa phải, tầm giá khoảng 1 triệu là vừa. Người khác lại cho rằng giai đoạn đầu là quan trọng nhất, vì giống như em bé tập nói, nếu người dạy nói sai thì sẽ nói sai mãi sau này. Cây đàn đầu tiên quyết định khả năng thẩm âm, độ tinh tế của đôi tai người chơi ngay giai đoạn đầu, nên phải mua đàn tốt, nếu không sẽ "hỏng tai", sau này chơi suốt ngày phải nhìn vào bản nhạc... Nói chung, mỗi người có ý kiến và một tiêu chuẩn khác nhau.'
    },
    {
        shopId: '-N5orBlfPXJ49qk6nOh_',
        name: 'Acoustic Rosen Xanh Đá G11SC 222',
        standardCost: 1500000,
        salePrice: 2840000,
        quantity: 1242,
        soldQuantity: 222,
        rating: 4.5,
        type: 1,
        img: ['server/guitar2_1.jpg', 'server/guitar2_2.jpg', 'server/guitar2_3.jpg', 'server/guitar2_4.jpg'],
        // discountId1
        discountId: '-N5orer-LorD7Z6lP83n',
        specifications: {
            brand: 'Rosen',
            origin: 'Trung Quốc',
            shape: 'D Thiếu',
            paintStyle: 'Sơn Mờ',
            top: 'Gỗ thông nguyên miếng',
            sideAndBack: 'Gỗ Gụ (Select Mahogany)',
            headstockAndNeck: 'Gỗ Nato',
            saddle: 'HPL',
            string: 'Rosen OEM',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Nhiều người mới học hoặc chưa bao giờ học guitar thường có tâm lý tìm mua một cây đàn "bình thường" để tập, sau này chơi tốt sẽ đổi sang cây đàn tốt hơn. Tuy nhiên, thế nào là cây đàn "bình thường" thì lại là điều khó định nghĩa, có người nói đàn gỗ thông, kỹ thuật sản xuất vừa phải, tầm giá khoảng 1 triệu là vừa. Người khác lại cho rằng giai đoạn đầu là quan trọng nhất, vì giống như em bé tập nói, nếu người dạy nói sai thì sẽ nói sai mãi sau này. Cây đàn đầu tiên quyết định khả năng thẩm âm, độ tinh tế của đôi tai người chơi ngay giai đoạn đầu, nên phải mua đàn tốt, nếu không sẽ "hỏng tai", sau này chơi suốt ngày phải nhìn vào bản nhạc... Nói chung, mỗi người có ý kiến và một tiêu chuẩn khác nhau.'
    },

    // shop1
    {
        shopId: '-N5orDJPkLtAxKuIjgOv',
        name: 'Classic Yamaha C80',
        standardCost: 3000000,
        salePrice: 4400000,
        quantity: 4321,
        soldQuantity: 2423,
        rating: 5,
        type: 0,
        img: ['server/guitar3_1.jpg', 'server/guitar3_2.jpg', 'server/guitar3_3.jpg', 'server/guitar3_4.jpg'],
        // discountId1
        discountId: '-N5oriJKyjKwd4R_tFrV',
        specifications: {
            brand: 'Yamaha',
            origin: 'Indonesia',
            shape: 'Cổ điển',
            paintStyle: 'Sơn Bóng',
            top: 'Gỗ Vân Sam',
            sideAndBack: 'Gỗ Nato',
            headstockAndNeck: 'Gỗ Gụ',
            saddle: 'HPL',
            string: 'Dây Yamaha',
            stringAdjustment: false,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Đàn Guitar Classic Yamaha C80 là model cao cấp nhất trong series C - series dành cho người mới bắt đầu của Yamaha. Ưu điểm vượt trội của model này so với 2 model còn lại C40 và C70 chính là sự trau chuốt trong tiếng đàn ở đẳng cấp cao hơn hẳn. Một sản phẩm không chỉ dành cho luyện tập mà còn có thể sử dụng trong các buổi trình diễn rất hiệu quả.'
    },
    {
        shopId: '-N5orDJPkLtAxKuIjgOv',
        name: 'Classic Yamaha C80 222',
        standardCost: 3000000,
        salePrice: 4440000,
        quantity: 4321,
        soldQuantity: 2423,
        rating: 5,
        type: 0,
        img: ['server/guitar3_1.jpg', 'server/guitar3_2.jpg', 'server/guitar3_3.jpg', 'server/guitar3_4.jpg'],
        // discountId1
        discountId: '-N5oriJKyjKwd4R_tFrV',
        specifications: {
            brand: 'Yamaha',
            origin: 'Indonesia',
            shape: 'Cổ điển',
            paintStyle: 'Sơn Bóng',
            top: 'Gỗ Vân Sam',
            sideAndBack: 'Gỗ Nato',
            headstockAndNeck: 'Gỗ Gụ',
            saddle: 'HPL',
            string: 'Dây Yamaha',
            stringAdjustment: false,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Đàn Guitar Classic Yamaha C80 là model cao cấp nhất trong series C - series dành cho người mới bắt đầu của Yamaha. Ưu điểm vượt trội của model này so với 2 model còn lại C40 và C70 chính là sự trau chuốt trong tiếng đàn ở đẳng cấp cao hơn hẳn. Một sản phẩm không chỉ dành cho luyện tập mà còn có thể sử dụng trong các buổi trình diễn rất hiệu quả.'
    },

    {
        shopId: '-N5orDJPkLtAxKuIjgOv',
        name: 'Classic Cordoba C5SP',
        standardCost: 5000000,
        salePrice: 7500000,
        quantity: 2222,
        soldQuantity: 1111,
        rating: 5,
        type: 0,
        img: ['server/guitar4_1.jpg', 'server/guitar4_2.jpg', 'server/guitar4_3.jpg', 'server/guitar4_4.jpg'],
        // discountId2
        discountId: '-N5orkKkVQ93dppEBr5a',
        specifications: {
            brand: 'Cordoba',
            origin: 'Tây Ban Nha',
            shape: 'Cổ điển',
            paintStyle: 'Sơn Bóng',
            top: 'Gỗ Vân Sam',
            sideAndBack: 'Gỗ Nato',
            headstockAndNeck: 'Gỗ Okoume',
            saddle: 'HPL',
            string: 'Savarez Cristal Corum',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Không có',
        },
        information: 'Cordoba là thương hiệu đến từ Tây Ban Nha được thành lập vào năm 1997, kể từ ngày thành lập đến nay Cordoba luôn tập trung vào việc mang lại cho người chơi những cây đàn guitar classic tốt nhất trên thị trường. Đàn guitar Classic thương hiệu Cordoba là sự pha trộn giữa sự khéo léo truyền thống của những người thợ bậc thầy với những phát triển công nghệ tiên tiến hiện đại. Tất cả những cây đàn của Cordoba đều có trọng lượng nhẹ, độ phản hồi cao, và kế thừa tất cả những giá trị truyền thống của đàn Tây Ban Nha. Giá của đàn guitar Cordoba cũng rất đa dạng cho mọi phân khúc từ những người mới chơi cho đến những người chơi chuyên nghiệp.'
    },
    {
        shopId: '-N5orDJPkLtAxKuIjgOv',
        name: 'Greg Bennett GD-100SGE',
        standardCost: 5000000,
        salePrice: 5660000,
        quantity: 2222,
        soldQuantity: 1111,
        rating: 5,
        type: 0,
        img: ['server/sample1.jpg', 'server/sample2.png'],
        // discountId2
        discountId: '-N5orkKkVQ93dppEBr5a',
        specifications: {
            brand: 'Taylor',
            origin: 'USA',
            shape: 'A Khuyết',
            paintStyle: 'Sơn mờ',
            top: 'Gỗ Thông Englemann (Laminated Englemann Spruce)',
            sideAndBack: 'Gỗ Okoume (Laminated Okoume)',
            headstockAndNeck: 'Gỗ Okoume',
            saddle: 'Gỗ Cẩm Lai(Rosewood)',
            string: 'Alice AW436',
            stringAdjustment: true,
            warranty: 12,
            eq: 'Amplifer Epiphone 15C',

        },
        information: 'Đàn Guitar Acoustic Mantic GT-1 thuộc dòng đàn entry level dành cho người mới bắt đầu. Với những thiết kế chuẩn mực của một cây đàn acoustic mantic GT-1 sẽ đáp ứng được nhu cầu tập luyện của bạn. Với thiết kế hiện đại của dòng đàn Mantic nổi tiếng GT-1 mang đậm chất tinh tế, nhẹ nhàng, không quá cầu kì, với ba mầu sắc được ưa chuộng nhất hiện nay là Vàng gỗ, Xanh ngọc và Đỏ mặt trời (Sunburst), GT-1 sẽ là điểm nhấn cho bạn trong mỗi cuộc giao lưu hội nhóm. Không chỉ đẹp về ngoại hình, GT-1 còn có âm thanh tốt, tiếng vang sáng, ngoài ra action đàn cực thấp nên những bạn mới chơi cũng có thể tiếp cận một cách dễ dàng.'
    },

];
export default products;