import ProfileScreen from "./ProfileScreen";
import OrderListScreen from "./OrderListScreen";
import OrderListCustomerScreen from "./Customer/OrderListCustomerScreen";
import OrderListSalesmanScreen from "./Salesman/OrderListSalesmanScreen";
import OrderDetailScreen from './Customer/OrderDetailScreen';
import OrderCancellationScreen from "./Customer/OrderCancellationScreen";
import TotalProductScreen from "./Salesman/TotalProductScreen";
import AddProductScreen from "./Salesman/AddProductScreen";
import TurnoverScreen from "./Salesman/TurnoverScreen";
export { ProfileScreen, OrderListScreen, OrderListCustomerScreen, OrderListSalesmanScreen, OrderDetailScreen, OrderCancellationScreen, TotalProductScreen, AddProductScreen, TurnoverScreen };